seed_api_responses = [

("Deer Mary, Please sends me the report by tomorow morning. I will needs to look over it befor the meeting on Wendsday. Thanks you, Jess", 

{'edits': [{'end': 4, 'error_type': 'R:NOUN', 'general_error_type': 'Grammar', 'id': '15819ee8-7e5f-571b-8502-2517488865ef', 'replacement': 'Dear', 'sentence': 'Deer Mary, Please sends me the report by tomorow morning.', 'sentence_start': 0, 'start': 0}, {'end': 23, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': 'd78e9d91-f14d-547d-a2dc-913a31ff59f1', 'replacement': 'send', 'sentence': 'Deer Mary, Please sends me the report by tomorow morning.', 'sentence_start': 0, 'start': 18}, {'end': 48, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': 'c1a133d3-52ea-5055-89c5-47e1d1468e97', 'replacement': 'tomorrow', 'sentence': 'Deer Mary, Please sends me the report by tomorow morning.', 'sentence_start': 0, 'start': 41}, {'end': 12, 'error_type': 'R:MORPH', 'general_error_type': 'Grammar', 'id': 'dd0d2db0-db2a-5c0a-9121-43a706ef3682', 'replacement': 'need', 'sentence': 'I will needs to look over it befor the meeting on Wendsday.', 'sentence_start': 58, 'start': 7}, {'end': 34, 'error_type': 'R:WO', 'general_error_type': 'Fluency/Style', 'id': 'affd2e57-c8cd-56c0-b981-d555e161eb92', 'replacement': 'it over before', 'sentence': 'I will needs to look over it befor the meeting on Wendsday.', 'sentence_start': 58, 'start': 21}, {'end': 58, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': '2e68cd02-a94c-5db8-b3ab-e1e9b18fd6c5', 'replacement': 'Wednesday', 'sentence': 'I will needs to look over it befor the meeting on Wendsday.', 'sentence_start': 58, 'start': 50}, {'end': 6, 'error_type': 'R:OTHER', 'general_error_type': 'Other', 'id': '932fc0da-7673-56ad-823e-74fa0d5b1c83', 'replacement': 'Thank', 'sentence': 'Thanks you, Jess', 'sentence_start': 118, 'start': 0}]}
),

("Hello everybody, This is an anouncement to state that there is now a new maintainance system in place. Please submits all requests acordingly.",

{'edits': [{'end': 39, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': '985ad71c-9d11-5a2d-9486-18517c3f72b6', 'replacement': 'announcement', 'sentence': 'Hello everybody, This is an anouncement to state that there is now a new maintainance system in place.', 'sentence_start': 0, 'start': 28}, {'end': 85, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': 'ce53d73c-a853-5045-8637-f35a677080da', 'replacement': 'maintenance', 'sentence': 'Hello everybody, This is an anouncement to state that there is now a new maintainance system in place.', 'sentence_start': 0, 'start': 73}, {'end': 14, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': '6028c2d5-f225-5142-a090-08da0be4fa17', 'replacement': 'submit', 'sentence': 'Please submits all requests acordingly.', 'sentence_start': 103, 'start': 7}, {'end': 38, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': '45967163-cd38-5ad0-9ebe-cb9654147ea0', 'replacement': 'accordingly', 'sentence': 'Please submits all requests acordingly.', 'sentence_start': 103, 'start': 28}]}
),

("I’m excited to attends the concert tomorow. Please lets me know if you would likes to go as well.",

{'edits': [{'end': 22, 'error_type': 'R:VERB:FORM', 'general_error_type': 'Grammar', 'id': '389e3691-7b68-578f-b14e-17c5cb943661', 'replacement': 'attend', 'sentence': 'I’m excited to attends the concert tomorow.', 'sentence_start': 0, 'start': 15}, {'end': 42, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': 'be4a3e28-0e56-5384-b635-818965f0a73c', 'replacement': 'tomorrow', 'sentence': 'I’m excited to attends the concert tomorow.', 'sentence_start': 0, 'start': 35}, {'end': 11, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': 'e3d2ac29-09e6-518f-b756-cc7015ebd9c7', 'replacement': 'let', 'sentence': 'Please lets me know if you would likes to go as well.', 'sentence_start': 44, 'start': 7}, {'end': 38, 'error_type': 'R:VERB:FORM', 'general_error_type': 'Grammar', 'id': '57ca2081-6b45-5798-81b1-affe20b3d70b', 'replacement': 'like', 'sentence': 'Please lets me know if you would likes to go as well.', 'sentence_start': 44, 'start': 33}]}
),

("I saw your proposal and liked it a lot much. I’ll will send you my feedback by tomorow morning.",

{'edits': [{'end': 43, 'error_type': 'U:ADJ', 'general_error_type': 'Grammar', 'id': '0974b3d0-923b-5a49-acb8-c160c25f4272', 'replacement': 'lot', 'sentence': 'I saw your proposal and liked it a lot much.', 'sentence_start': 0, 'start': 35}, {'end': 4, 'error_type': 'U:OTHER', 'general_error_type': 'Other', 'id': '3abac2d5-0bcd-59f7-a967-344aebdad3b9', 'replacement': 'I', 'sentence': 'I’ll will send you my feedback by tomorow morning.', 'sentence_start': 45, 'start': 0}, {'end': 41, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': '69fd5f13-346e-5aab-8ab1-4117bbf5ce48', 'replacement': 'tomorrow', 'sentence': 'I’ll will send you my feedback by tomorow morning.', 'sentence_start': 45, 'start': 34}]}
),

("I have had returned the documents with miniscule adjustments. Please reviews and return the document by Wendsday.",

{'edits': [{'end': 11, 'error_type': 'U:VERB:TENSE', 'general_error_type': 'Grammar', 'id': '61774010-5361-591b-881c-e06e26d5dcb4', 'replacement': '', 'sentence': 'I have had returned the documents with miniscule adjustments.', 'sentence_start': 0, 'start': 7}, {'end': 14, 'error_type': 'R:MORPH', 'general_error_type': 'Grammar', 'id': '580b3104-6e54-5efa-b0fe-655e263b0f6f', 'replacement': 'review', 'sentence': 'Please reviews and return the document by Wendsday.', 'sentence_start': 62, 'start': 7}, {'end': 50, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': 'f9ad6ae8-bb33-5958-8fb5-4ebfecc3f67c', 'replacement': 'Wednesday', 'sentence': 'Please reviews and return the document by Wendsday.', 'sentence_start': 62, 'start': 42}]}
),

("Deer Carrie, Thank you so much for the lovely jewlry. I absolutely adores it. I hope all are well with you and hope to see you very much soon.",

{'edits': [{'end': 18, 'error_type': 'R:NOUN', 'general_error_type': 'Grammar', 'id': '83a7ca87-b1f8-56d3-a6cb-1a1e6413c94a', 'replacement': 'Dear Carrie, thank', 'sentence': 'Deer Carrie, Thank you so much for the lovely jewlry.', 'sentence_start': 0, 'start': 0}, {'end': 52, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': 'dab938cc-8194-5079-8293-6f040e909dc4', 'replacement': 'jewelry', 'sentence': 'Deer Carrie, Thank you so much for the lovely jewlry.', 'sentence_start': 0, 'start': 46}, {'end': 19, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': '038d6a06-2502-55db-948f-a29e9917249b', 'replacement': 'adore', 'sentence': 'I absolutely adores it.', 'sentence_start': 54, 'start': 13}, {'end': 14, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': '2fa269c9-c8a4-5d38-9ab8-e20cee01e1be', 'replacement': 'is', 'sentence': 'I hope all are well with you and hope to see you very much soon.', 'sentence_start': 78, 'start': 11}]}
),

("Deer Mark, I just wanted to say to thank you for the lovely graduaition gift. I will have use it every day. I hope you had a grate time at the party.",

{'edits': [{'end': 4, 'error_type': 'R:NOUN', 'general_error_type': 'Grammar', 'id': 'd1d97952-41f0-5083-afbd-deb5be07da33', 'replacement': 'Dear', 'sentence': 'Deer Mark, I just wanted to say to thank you for the lovely graduaition gift.', 'sentence_start': 0, 'start': 0}, {'end': 35, 'error_type': 'U:VERB:FORM', 'general_error_type': 'Grammar', 'id': '999ead4a-54eb-5ea6-8e8e-f4e90e7e84a9', 'replacement': '', 'sentence': 'Deer Mark, I just wanted to say to thank you for the lovely graduaition gift.', 'sentence_start': 0, 'start': 32}, {'end': 71, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': '00b64ff6-306f-5775-90b2-75e07b1c5869', 'replacement': 'graduation', 'sentence': 'Deer Mark, I just wanted to say to thank you for the lovely graduaition gift.', 'sentence_start': 0, 'start': 60}, {'end': 15, 'error_type': 'M:VERB:FORM', 'general_error_type': 'Grammar', 'id': '20178dd5-9222-5847-9f9d-9f3d09539204', 'replacement': 'to use', 'sentence': 'I will have use it every day.', 'sentence_start': 78, 'start': 12}, {'end': 22, 'error_type': 'R:ADJ', 'general_error_type': 'Grammar', 'id': '90b4fa2b-0ea0-5d44-aa48-36a8101e866b', 'replacement': 'great', 'sentence': 'I hope you had a grate time at the party.', 'sentence_start': 108, 'start': 17}]}
),

("To whom it may concerns, I have not yet recieved the product I had ordered last week. Please let me know if it’s on it’s way.",

{'edits': [{'end': 23, 'error_type': 'R:VERB:FORM', 'general_error_type': 'Grammar', 'id': '99fabc7c-2156-52a9-861e-d9c55e1384ec', 'replacement': 'concern', 'sentence': 'To whom it may concerns, I have not yet recieved the product I had ordered last week.', 'sentence_start': 0, 'start': 15}, {'end': 48, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': 'a04621ef-99e5-5457-836a-bebbb7bf4c7a', 'replacement': 'received', 'sentence': 'To whom it may concerns, I have not yet recieved the product I had ordered last week.', 'sentence_start': 0, 'start': 40}, {'end': 67, 'error_type': 'U:VERB:TENSE', 'general_error_type': 'Grammar', 'id': '0b74805b-852b-52b9-9791-587e7b086061', 'replacement': '', 'sentence': 'To whom it may concerns, I have not yet recieved the product I had ordered last week.', 'sentence_start': 0, 'start': 63}, {'end': 34, 'error_type': 'R:DET', 'general_error_type': 'Grammar', 'id': '9ce12187-fd1f-523d-b7be-dfd73fe74028', 'replacement': 'it’s on its', 'sentence': 'Please let me know if it’s on it’s way.', 'sentence_start': 86, 'start': 22}]}
),

("Hello, I just had wanted to let you know that the report’s on it’s way.",

{'edits': [{'end': 18, 'error_type': 'U:VERB:TENSE', 'general_error_type': 'Grammar', 'id': '5fc82951-478c-589a-9aaf-424dcf8e65a8', 'replacement': '', 'sentence': 'Hello, I just had wanted to let you know that the report’s on it’s way.', 'sentence_start': 0, 'start': 14}, {'end': 66, 'error_type': 'R:DET', 'general_error_type': 'Grammar', 'id': 'd03f920a-16f9-5f02-87ec-0845e333d102', 'replacement': 'report’s on its', 'sentence': 'Hello, I just had wanted to let you know that the report’s on it’s way.', 'sentence_start': 0, 'start': 50}]}
),

("The board of directors believe that a new strategy are necessary. Committee members was divided on the proposed changes.",

{'edits': [{'end': 54, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': 'ffa1f6f3-6053-55eb-b791-017ddfc95909', 'replacement': 'is', 'sentence': 'The board of directors believe that a new strategy are necessary.', 'sentence_start': 0, 'start': 51}, {'end': 21, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': 'cda04657-18c3-52b6-9b14-ac651a4e2cfe', 'replacement': 'were', 'sentence': 'Committee members was divided on the proposed changes.', 'sentence_start': 66, 'start': 18}]}
),

("The organization's goals and objectives is well-defined. However, the project managers and stakeholders has conflicting views. There will be a meeting tommorow to clarify goals.",

{'edits': [{'end': 42, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': '38ba6979-59ab-577f-8408-b12e9557104a', 'replacement': 'are', 'sentence': "The organization's goals and objectives is well-defined.", 'sentence_start': 0, 'start': 40}, {'end': 50, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': 'b2ef7c75-9b08-5b98-ab74-4f0abb99e8c1', 'replacement': 'have', 'sentence': 'However, the project managers and stakeholders has conflicting views.', 'sentence_start': 57, 'start': 47}, {'end': 32, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': '940b83ec-c211-5b6e-aea3-a5da6af7c064', 'replacement': 'tomorrow', 'sentence': 'There will be a meeting tommorow to clarify goals.', 'sentence_start': 127, 'start': 24}]}
),

("Unfortunately, issues was discovered in the latest batch of products.  The sales team and customer support is working closely together to solve the problems before tomorow morning.",

{'edits': [{'end': 25, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': 'c2c70d9f-38de-57a3-b727-c8834576e2be', 'replacement': 'were', 'sentence': 'Unfortunately, issues was discovered in the latest batch of products.', 'sentence_start': 0, 'start': 22}, {'end': 38, 'error_type': 'R:VERB:SVA', 'general_error_type': 'Grammar', 'id': '213bd035-a27f-50a0-9193-1c6351822487', 'replacement': 'are', 'sentence': 'The sales team and customer support is working closely together to solve the problems before tomorow morning.', 'sentence_start': 71, 'start': 36}, {'end': 100, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': '2c383624-7b5a-5d65-a536-fecd3e1bfe05', 'replacement': 'tomorrow', 'sentence': 'The sales team and customer support is working closely together to solve the problems before tomorow morning.', 'sentence_start': 71, 'start': 93}]}
),

("I have had returned the documents with miniscule adjustments. Let me know if you’ve recieved it. Please reviews and return the document by Wendsday.",

{'edits': [{'end': 11, 'error_type': 'U:VERB:TENSE', 'general_error_type': 'Grammar', 'id': '61774010-5361-591b-881c-e06e26d5dcb4', 'replacement': '', 'sentence': 'I have had returned the documents with miniscule adjustments.', 'sentence_start': 0, 'start': 7}, {'end': 36, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': '7d40fdb1-2a2a-5a23-91b1-f1e5e211712a', 'replacement': 'received', 'sentence': 'Let me know if you have not recieved it.', 'sentence_start': 62, 'start': 28}, {'end': 14, 'error_type': 'R:MORPH', 'general_error_type': 'Grammar', 'id': '580b3104-6e54-5efa-b0fe-655e263b0f6f', 'replacement': 'review', 'sentence': 'Please reviews and return the document by Wendsday.', 'sentence_start': 103, 'start': 7}, {'end': 50, 'error_type': 'R:SPELL', 'general_error_type': 'Spelling', 'id': 'f9ad6ae8-bb33-5958-8fb5-4ebfecc3f67c', 'replacement': 'Wednesday', 'sentence': 'Please reviews and return the document by Wendsday.', 'sentence_start': 103, 'start': 42}]}
)
]
